android.builtInKotlin=false
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=false
android.newDsl=false
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.uniquePackageNames=false
android.useAndroidX=true
android.usesSdkInManifest.disallowed=false
org.gradle.jvmargs=-Xmx256m -XX:+UseSerialGC -XX:MaxMetaspaceSize=160m -XX:CICompilerCount=1 -Xss512k -XX:ReservedCodeCacheSize=32m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
org.gradle.daemon=false
org.gradle.workers.max=1

android.suppressUnsupportedCompileSdk=35
