plugins {
    id 'com.android.application'
}

android {
    namespace 'com.clipboardfix'
    compileSdk 35

    defaultConfig {
        applicationId "com.clipboardfix"
        minSdk 28
        targetSdk 35
        versionCode 6
        versionName "1.3"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packagingOptions {
        exclude 'META-INF/**'
        exclude 'kotlin/**'
        exclude '**.bin'
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
    implementation 'androidx.core:core:1.12.0'

    // DexKit：精确定位 com.miui.provider.InputProvider 的包名校验方法
    implementation 'org.luckypray:dexkit:2.2.0'
}
